controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_controller:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api/{version}
    name_prefix: 'api_'
    trailing_slash_on_root: false
